---
- hosts: localhost
  become: true
  gather_facts: no

  tasks:
  - name: Build New Docker Image
    docker_image:
      path: ../tomcat
      name: docker.io/yadudock/tc
      tag: BUILD_ID
    register: docker_build

  # - name: 'Retag image'
  #   shell: docker tag yadudock/abdemotc:latest yadudock/tc:latest
  #   when: docker_build.changed
  
  - name: Log into DockerHub
    docker_login:
      # registry: docker.io
      username: yadudock
      password: 1928yadu9325
      email: yadusrb@gmail.com
      reauthorize: yes
    when: docker_build.changed

  - name: Tag and push to docker hub latest
    docker_image:
      name: yadudock/tc:BUILD_ID
      repository: docker.io/yadudock/tc:BUILD_ID
      push: yes
    when: docker_build.changed

  # - name: Tag and push to docker hub dev
  #   docker_image:
  #     name: yadudock/abdemotc:latest
  #     repository: docker.io/yadudock/abdemotc:dev
  #     push: yes
  #   when: docker_build.changed

  - name: 'Remove Local Images'
    shell: docker rmi -f yadudock/tc:BUILD_ID
    # shell: docker rmi -f yadudock/abdemotc:latest yadudock/abdemotc:dev

  - name: Log out of DockerHub
    docker_login:
      state: absent
    when: docker_build.changed
